## numpy基础

#### core代码由C语言写成

numpy导包

In [2]:
import numpy as np

In [22]:
a=np.array([1,2,3])
print(a)
print(type(a))
print a[1]
a[2]=123
print a

[1 2 3]
<type 'numpy.ndarray'>
2
[  1   2 123]


In [27]:
b=np.array([[1,2,3],[2,3,5]])
print(b)
print(type(b))          #<class 'numpy.ndarray'>
b[1][1]

[[1 2 3]
 [2 3 5]]
<type 'numpy.ndarray'>


3

In [28]:
print(b.shape)

(2L, 3L)


In [31]:
print(b[0,2])

3


ndarray = n dimensional array

内置函数--》创建数组

In [34]:
a = np.zeros((2,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [35]:
b=np.ones((1,2))
print(b)

[[ 1.  1.]]


In [36]:
c=np.full((2,2),8)
print(c)

[[8 8]
 [8 8]]


In [37]:
d=np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


产生全部为0-1的随机数

In [39]:
e=np.random.random((3,2))
print(e)

[[ 0.60216778  0.19674232]
 [ 0.86439458  0.68291439]
 [ 0.4674095   0.96515589]]


In [40]:
f=np.empty((2,3,4))    # 分配一批内存给它，内存中残存数据
print(f)

[[[  4.05407621e-316   7.65931078e-316   4.04587195e-316   7.65931552e-316]
  [  4.49179110e-316   7.65931789e-316   4.04587195e-316   7.65932026e-316]
  [  4.49179110e-316   7.65932263e-316   4.04587195e-316   7.65932501e-316]]

 [[  4.49179110e-316   7.65932738e-316   4.04587195e-316   7.65932975e-316]
  [  4.49179110e-316   7.65933212e-316   4.04587195e-316   7.65933686e-316]
  [  4.49179110e-316   7.65933923e-316   4.04587195e-316   7.65348555e-316]]]


In [41]:
print(f.shape)

(2L, 3L, 4L)


In [42]:
g=np.arange(15)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
print(g.shape)

(15L,)


, 逗号定义一个tuple

In [44]:
type((2,3))

tuple

数组可以有不同的数据类型
int32,int64,float64

In [45]:
arr=np.array([1,2,3])
print(arr.dtype)

int32


In [258]:
arr=np.array([1,2,3],dtype=np.float64)
print(arr.dtype)

float64


In [47]:
arr

array([ 1.,  2.,  3.])

In [48]:
arr=np.array([1,2,3],dtype=np.int64)
print(arr.dtype)

int64


生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型<br/>
使用**astype**复制数组并转换数据类型

In [49]:
int_arr=np.array([1,2,3,4,5])
print(int_arr,int_arr.dtype)

(array([1, 2, 3, 4, 5]), dtype('int32'))


In [50]:
float_arr=int_arr.astype(np.float)
print(float_arr.dtype,float_arr)

(dtype('float64'), array([ 1.,  2.,  3.,  4.,  5.]))


使用**astype**将float转换为**int**时小数部分被舍弃

In [51]:
float_arr=np.array([3.5,2.3,4.8,-2.2])
print(float_arr)

[ 3.5  2.3  4.8 -2.2]


In [52]:
int_arr = float_arr.astype(np.int)  # int默认为int32
print(int_arr,int_arr.dtype)

(array([ 3,  2,  4, -2]), dtype('int32'))


使用**astype**把字符串转换为数组，如果失败则抛出异常

In [259]:
str_arr = np.array(['1.23','2.2','25.4'],dtype=np.string_)     #string需要下划线
print(str_arr.dtype)

|S4


In [260]:
float_arr=str_arr.astype(dtype=np.float)
print(float_arr)

[  1.23   2.2   25.4 ]


**astype**使用其他数组的数据类型作为参数

In [57]:
int_arr=np.arange(10)
float_arr = np.array([2.3,3.5,4.7])
print(float_arr.dtype,int_arr.dtype)

(dtype('float64'), dtype('int32'))


In [58]:
int_arr.astype(dtype=float_arr.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

## Array indexing/数组取值和赋值

Numpy提供多种取值方式

In [71]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3L, 4L)


### 切片

多维数组可以从各个维度同时切片

In [80]:
b =a[:,:2]
print(b)
c=a[0:2,2:4]
print(c)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[3 4]
 [7 8]]


b只是一个指针，指向a，并没有一个新的内存空间存储b

In [72]:
c[0,0]=423
print(c)
print('----------------')
print(a)

[[423   4]
 [  7   8]]
----------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


若要创建新的内存地址，则需使用<font color='red'>**copy()**</font>

In [79]:
narCopy=a.copy()
print(narCopy)
narCopy[0,0]=423
print(narCopy)
print a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[423   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 两种区别
两种arr.shape的区别!!!

In [81]:
row_r1=a[1,:]
print(row_r1,row_r1.shape)

(array([5, 6, 7, 8]), (4L,))


In [82]:
row_r2=a[1:2,:]    #表示第1行
print(row_r2,row_r2.shape)

(array([[5, 6, 7, 8]]), (1L, 4L))


In [84]:
row_r3=a[[1],:]
print(row_r3,row_r3.shape)

(array([[5, 6, 7, 8]]), (1L, 4L))


## 高级用法

In [86]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [90]:
print a[[0,1,2],[0,1,0]]    #将a矩阵中的(0,0)(1,1)(2,0)取出来
print a[[0,1,2],[0,1,0]].shape

[1 4 5]
(3L,)


a[[0,1,2],[0,1,0]]    等价于+++》   [a[0,0],a[1,1],a[2,0]]

In [93]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [96]:
print a
print(a[[0,1],[0,0]])
print '===='
print([a[0,0],a[1,0]])

[[1 2]
 [3 4]
 [5 6]]
[1 3]
====
[1, 3]


In [99]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print a
b=np.array([0,2,0,1])
print('----------------')
print(a[np.arange(4),b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
----------------
[ 1  6  7 11]


In [100]:
a[np.arange(4),b]+=10
print a

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


#### 用条件判定去取(好用)

In [101]:
a=np.array([[1,2],[3,4],[5,6]])
print a

[[1 2]
 [3 4]
 [5 6]]


In [105]:
bool_index=(a>2)
print(bool_index)
print ''
print(a[bool_index])
print(a[bool_index].shape)

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]
(4L,)


#### 用一句话完成上述操作

In [106]:
print(a[a>2])

[3 4 5 6]


![numpy](img/numpy/numpy_1.png)
![numpy](img/numpy/numpy_2.png)

## Datatypes

可以使用**dtype** 查看numpy数组中元素的类型：

In [108]:
x=np.array([1,2])
y=np.array([1.0,2.0])
z=np.array([1,2],dtype=np.int64)

In [110]:
print(x.dtype,y.dtype,z.dtype)

(dtype('int32'), dtype('float64'), dtype('int64'))


## 数值计算

<font color='blue'><strong>经常会用到</strong></font>

In [115]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print x
print y
print(x.shape,y.shape)
print x.shape+y.shape

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]
((2L, 2L), (2L, 2L))
(2L, 2L, 2L, 2L)


**逐元素求和**，有下面2种方式：

In [116]:
x+y

array([[  6.,   8.],
       [ 10.,  12.]])

In [117]:
np.add(x,y)

array([[  6.,   8.],
       [ 10.,  12.]])

**逐元素相减**

In [118]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [119]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

**逐元素相乘**

In [120]:
x*y

array([[  5.,  12.],
       [ 21.,  32.]])

In [122]:
np.multiply(x,y)

array([[  5.,  12.],
       [ 21.,  32.]])

**逐元素相除**

In [123]:
x/y

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [124]:
np.divide(x,y)

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

**逐元素求平方根**

In [125]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

## Martix Multiplication 矩阵相乘

In [127]:
v = np.array([9,10])
w = np.array([10,11])
print v.shape

(2L,)


In [128]:
v.dot(w)

200

等价于：

In [129]:
np.dot(v,w)

200

### 矩阵的乘法

In [132]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]
()
[[5 6]
 [7 8]]


In [133]:
v

array([ 9, 10])

In [134]:
print(x.dot(v))

[29 67]


等价于：

In [137]:
np.dot(x,v)

array([29, 67])

In [145]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [146]:
x.dot(y)

array([[19, 22],
       [43, 50]])

### 转置

In [147]:
x

array([[1, 2],
       [3, 4]])

In [148]:
x.T

array([[1, 3],
       [2, 4]])

一维的vector转置后还是自己

In [151]:
v.T

array([ 9, 10])

In [153]:
w=np.array([1,2,3])
print(w,w.shape)

(array([1, 2, 3]), (3L,))


In [155]:
print(w.T,w.T.shape)

(array([1, 2, 3]), (3L,))


#### 利用转置矩阵做dot product/点乘

In [159]:
arr=np.random.random([6,3])
arr

array([[ 0.64035082,  0.99082856,  0.33196379],
       [ 0.93303415,  0.2000728 ,  0.16579561],
       [ 0.90957299,  0.17512825,  0.67873004],
       [ 0.64032977,  0.74099931,  0.4826136 ],
       [ 0.37506745,  0.02941928,  0.22921924],
       [ 0.78130087,  0.34139142,  0.28263117]])

In [160]:
print(arr.T.dot(arr))

[[ 3.26905378  1.7326921   1.60044528]
 [ 1.7326921   1.71893384  0.94180287]
 [ 1.60044528  0.94180287  0.96370034]]


高维的tensor也可以做转置

In [161]:
arr=np.arange(16).reshape(2,2,4)
print(arr,arr.shape)

(array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]]), (2L, 2L, 4L))


In [162]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [163]:
print(arr.transpose(0,2,1))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [164]:
print(arr.transpose(2,1,0))

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


#### 转置也可以使用swapaxes

In [165]:
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [166]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print(x)
print()
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
()
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [172]:
np.matmul(x,y)

array([[[ 28,  34],
        [ 76,  98],
        [124, 162]],

       [[172, 226],
        [220, 290],
        [268, 354]]])

In [174]:
np.matmul(x,y).shape

(2L, 3L, 2L)

### 常用运算

In [175]:
x = np.array([[1,2],[3,4]])
print x

[[1 2]
 [3 4]]


#### 求和！

In [176]:
print np.sum(x)
print x.sum()

10
10


对x的第0维（列）求和

In [177]:
print np.sum(x,axis=0)

[4 6]


对x的第1维（行）求和

In [178]:
print np.sum(x,axis=1)

[3 7]


#### 求平均！

In [183]:
print x
print(np.mean(x))
print(x.mean())
print(np.mean(x,axis=0))
print(np.mean(x,axis=1))

[[1 2]
 [3 4]]
2.5
2.5
[ 2.  3.]
[ 1.5  3.5]


#### Cumulative Sum 累加求和！

In [188]:
print x
print('--------列叠加--------')
print(x.cumsum(axis=0))
print('--------行叠加--------')
print(x.cumsum(axis=1))

[[1 2]
 [3 4]]
--------列叠加--------
[[1 2]
 [4 6]]
--------行叠加--------
[[1 3]
 [3 7]]


In [190]:
print(x.cumprod(axis=0))
print(x.cumprod(axis=1))

[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]


### 一维数组排序

In [195]:
arr = np.random.randn(8) *10
print arr

[  1.38692252  -8.33732043  -7.69408548  -2.18167579  15.04691023
 -19.1699793    3.83186182   0.31336915]


In [196]:
arr.sort()
print(arr)

[-19.1699793   -8.33732043  -7.69408548  -2.18167579   0.31336915
   1.38692252   3.83186182  15.04691023]


### 二维数组在某些维度上排序

In [197]:
arr = np.random.randn(5,3) *10
print arr

[[  3.53572785 -10.12999801  16.74419665]
 [ -7.78701186   1.25716822  -7.4153334 ]
 [  4.86139607   2.62838226   5.91792859]
 [  4.9244698   30.13701832  -0.91301592]
 [  6.76537381  -4.9731472    7.85233546]]


In [199]:
arr.sort(1)   # 在第1维上进行排序，即在行上进行排序
print(arr)

[[-10.12999801   3.53572785  16.74419665]
 [ -7.78701186  -7.4153334    1.25716822]
 [  2.62838226   4.86139607   5.91792859]
 [ -0.91301592   4.9244698   30.13701832]
 [ -4.9731472    6.76537381   7.85233546]]


#### 找出排序后位置在5%的数字

In [205]:
large_arr=np.random.randn(1000)*10
large_arr.sort()
print(large_arr[int(0.05*len(large_arr))])

-16.9068732328


## Broadcasting

<font color='red'><b>empty_likc</b></font>

In [212]:
x=np.array([[2,3,4],[5,6,7],[8,9,10]])
print x.shape
y=np.empty_like(x)
print(y)

(3L, 3L)
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 逻辑运算

<font color=red>**np.where(cond,x_arr,y_arr)**</font><br/>
根据cond数组中的值选择x_arr还是y_arr，True则选择前者，False则选择后者

In [213]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])
cond=np.array([True,False,True,True,False])
print(np.where(cond,x_arr,y_arr))

[ 1.1  2.2  1.3  1.4  2.5]


In [214]:
arr = np.random.randn(4,4)
print arr

[[ 0.62426898 -2.16518761 -1.13379932  0.58931706]
 [-0.46429424  0.81550041 -0.62715406  0.05340905]
 [-0.43797516  1.9778459  -0.85932972 -0.3742061 ]
 [ 0.40005214 -0.81229452  1.1794454   0.90895641]]


In [215]:
arr>0

array([[ True, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False, False],
       [ True, False,  True,  True]], dtype=bool)

#### np.where(cond,x,y) 应用

In [216]:
print np.where(arr>0,1,-1)

[[ 1 -1 -1  1]
 [-1  1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1  1  1]]


In [217]:
print(np.where(arr>0,0,arr))

[[ 0.         -2.16518761 -1.13379932  0.        ]
 [-0.46429424  0.         -0.62715406  0.        ]
 [-0.43797516  0.         -0.85932972 -0.3742061 ]
 [ 0.         -0.81229452  0.          0.        ]]


## 一些更高级的ndarray处理

### 使用reshape来改变tensor的形状
numpy可以很容易地把一维数组转为二维数组，或三位数组

In [223]:
arr = np.arange(8)
print arr.reshape(2,4)
print('')
print arr.reshape(2,2,2)

[[0 1 2 3]
 [4 5 6 7]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


如果**reshape**的某一个维度上写上**-1**，numpy会自动推到出正确的维度

In [224]:
arr = np.arange(15)
print(arr.reshape(5,-1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [227]:
other_arr=np.ones((3,5))
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

高维数组可以用**ravel**来拉平

In [229]:
arr=arr.reshape(other_arr.shape)
print(arr.ravel())
print(arr.ravel().shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15L,)


## 连接两个二维数组

In [239]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print arr1
print arr2

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [238]:
## 连接
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [240]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [241]:
np.vstack((arr1,arr2))  # vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [242]:
np.hstack((arr1,arr2)) # horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### 拆分数组

In [243]:
arr = np.random.rand(5,5)
print arr

[[ 0.32549921  0.32757266  0.67444617  0.50956633  0.27032211]
 [ 0.50089867  0.05543758  0.81247112  0.81383294  0.36104746]
 [ 0.03858709  0.89163677  0.62862917  0.60150385  0.80660274]
 [ 0.06845234  0.00203142  0.43337157  0.72418676  0.29570457]
 [ 0.32932534  0.02387714  0.42388603  0.8895442   0.96551023]]


In [248]:
first,second,third = np.split(arr,[1,3],axis=0)
print(first)
print('')
print(second)
print('')
print(third)

[[ 0.32549921  0.32757266  0.67444617  0.50956633  0.27032211]]

[[ 0.50089867  0.05543758  0.81247112  0.81383294  0.36104746]
 [ 0.03858709  0.89163677  0.62862917  0.60150385  0.80660274]]

[[ 0.06845234  0.00203142  0.43337157  0.72418676  0.29570457]
 [ 0.32932534  0.02387714  0.42388603  0.8895442   0.96551023]]


### 堆叠辅助

In [250]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = np.random.randn(3,2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]
 [4 5]]
[[ 0.05521468 -0.07215548]
 [ 1.66014816  0.6274348 ]
 [ 0.40907562  0.80481401]]


### r_用于按行堆叠

In [255]:
print(np.r_[arr1,arr2])
print('')

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [ 0.05521468 -0.07215548]
 [ 1.66014816  0.6274348 ]
 [ 0.40907562  0.80481401]]



### c_用于按行堆叠

In [257]:
print(np.c_[arr1,arr2],arr)
print('')

(array([[ 0.        ,  1.        ,  0.05521468, -0.07215548],
       [ 2.        ,  3.        ,  1.66014816,  0.6274348 ],
       [ 4.        ,  5.        ,  0.40907562,  0.80481401]]), array([0, 1, 2, 3, 4, 5]))



切片直接转为数组